htmlx_demo/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('siting.urls', 'siting'), namespace='siting')),
]

siting/urls.py
from django.urls import path

from siting.views import AnimalView, BreedView, SitingView, HomeView, DateView


urlpatterns = [
    path('animals/', AnimalView.as_view(), name='animals_list'),
    path('breeds/', BreedView.as_view(), name='breeds_list'),
    path('sitings/', SitingView.as_view(), name='sitings_list'),
    path('dates/', DateView.as_view(), name='date_list'),
    path('', HomeView.as_view(), name='home'),
]

siting/models.py
from uuid import uuid4

from django.contrib.auth.models import AbstractUser
from django.db import models


class BaseModel(models.Model):
    id = models.UUIDField(default=uuid4, primary_key=True, editable=False, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        abstract = True
        ordering = ['-created_at']


class Animal(BaseModel):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Breed(BaseModel):
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return f'{self.name} - {self.animal.name}'


class Siting(BaseModel):
    breed = models.ForeignKey(Breed, on_delete=models.CASCADE)
    date = models.DateField()

    class Meta:
        unique_together = [['breed_id', 'date',]]

    def __str__(self):
        return f'{self.breed.name} - {self.breed.animal.name} - {self.date}'

siting/views.py
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt

from siting.models import Animal, Breed, Siting


class HomeView(View):
    http_method_names = ['get']

    def get(self, request):
        return render(request, 'siting/home.html')


class AnimalView(View):
    http_method_names = ['get']

    def get(self, request):
        animals = Animal.objects.all()
        animals_list = '<option value=""></option>'

        for animal in animals:
            animals_list += f'<option value="{animal.id}">{animal.name}</option>'

        response = f'''<div class="form-group">
                            <label for="animalInput">Animal</label>
                            <select class="form-control" id="animalInput" name="animal_id" hx-trigger="change" hx-post="/breeds/" hx-target="#breedsList" required>
                                {animals_list}
                            </select>
                        </div>
                            <div id="breedsList"></div>
                            <button type="submit" class="btn btn-primary mt-2" hx-target="#message">Save</button>
                            <button type="button" class="btn btn-danger mt-2 ml-2" hx-trigger="click" hx-get="/breeds/" hx-target="#animalsList">Cancel</button>
                        '''
        return HttpResponse(response)


@method_decorator(csrf_exempt, name='dispatch')
class BreedView(View):
    http_method_names = ['get', 'post']

    def get(self, request):
        return HttpResponse('')

    def post(self, request):
        animal_id = request.POST.get('animal_id', None)

        if animal_id is None:
            return HttpResponse('Error: Animal ID is required')

        breeds_list = '<option value=""></option>'
        breeds = Breed.objects.filter(animal_id=animal_id)

        for breed in breeds:
            breeds_list += f'<option value="{breed.id}">{breed.name}</option>'

        response = f'''<div class="form-group">
                            <label for="breedInput">Breed</label>
                            <select class="form-control" id="breedInput" name="breed_id"  required>
                                {breeds_list}
                            </select>
                        </div>
                        
                        '''
                        
        return HttpResponse(response)


class DateView(View):
    http_method_names = ['get']

    def get(self, request):
        response = f'''<div class="form-group">
                            <label for="dateInput">Date</label>
                            <input type="date" class="form-control" id="dateInput" name="date" required>
                        </div>
                        '''
        return HttpResponse(response)


@method_decorator(csrf_exempt, name='dispatch')
class SitingView(View):
    http_method_names = ['get', 'post', 'delete']

    def get_sitings(self):
        response = ''
        sitings = Siting.objects.all()
        for idx, siting in enumerate(sitings):
            response += f'''<tr>
                            <th scope="row">{idx+1}</th>
                            <td>{siting.breed.animal.name}</td>
                            <td>{siting.breed.name}</td>
                            <td>{siting.date}</td>
                            <td><button hx-trigger="click" hx-delete="/sitings/?siting_id={siting.id}" hx-target="#sitings_list" class="btn btn-sm btn-danger" type="button">DELETE</button></td>
                            </tr>'''
        
        return response

    def get(self, request):
        return HttpResponse(self.get_sitings())


    def post(self, request):
        try:
            breed_id = request.POST.get('breed_id', None)
            date = request.POST.get('date', None)

            if None in (breed_id, date):
                raise Exception('breed_id and date are required!')

            _, created = Siting.objects.get_or_create(breed_id=breed_id, date=date)

            if not created:
                return HttpResponse('Record already exists')

            return HttpResponse('')

        except Exception as e:
            return HttpResponse(f'Error: {str(e)}')


    def delete(self, request):
        try:
            siting_id = request.GET.get('siting_id', None)

            if siting_id is None:
                raise Exception('Siting ID is required!')

            _ = Siting.objects.get(id=siting_id).delete()

            return HttpResponse(self.get_sitings())

        except Exception as e:
            return HttpResponse(f'Error: {str(e)}')

siting/templates/siting/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HTMX - Demo</title>
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.1/css/bootstrap.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/htmx/1.7.0/htmx.min.js"></script>
</head>

<body>
    <div class="container">
        <div class="row mt-2">
            <div class="col-lg-2"></div>
            <div class="col-lg-8 text-center">
                <h1>HTMX - Demo</h1>
            </div>
        </div>

        <div class="row mt-4">
            <div class="col-lg-1"></div>
            <div class="col-lg-10">
                <h3>Siting List:</h3>
            </div>
        </div>

        <div class="row mt-4">
            <div class="col-lg-1"></div>
            <div class="col-lg-10">
                <table class="table" hx-get="{% url 'siting:sitings_list' %}" hx-target="#sitings_list"
                    hx-trigger="load, every 1s">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Animal</th>
                            <th scope="col">Breed</th>
                            <th scope="col">Date</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody id="sitings_list">
                    </tbody>
                </table>
            </div>
        </div>

        <div class="row mt-4">
            <div class="col-lg-1"></div>
            <div class="col-lg-10">
                <button type="button" class="btn btn-primary btn-lg" hx-trigger="click" hx-get="{% url 'siting:animals_list' %}" hx-target="#animalsList">New</button>
            </div>
        </div>

        <div class="row mt-4">
            <div class="col-lg-1"></div>
            <div class="col-lg-4">
                <div id="message"></div>
                <form hx-post="{% url 'siting:sitings_list' %}" hx-target="#animalsList">
                    <div class="form-group">
                        <label for="dateInput">Date</label>
                        <input type="date" class="form-control" id="dateInput" name="date" required>
                    </div>
                    <div id="animalsList"></div>            
                </form>
            </div>
        </div>
    </div>
</body>

</html>